# -*- coding: utf-8 -*-
"""
Havacılık kodları için açıklama sözlükleri.
Bu modül, METAR, TAF ve SYNOP raporlarında kullanılan kodların
Türkçe ve İngilizce açıklamalarını içerir.
"""

# Halihazır Hava (Present Weather - ww) Kodları
WW_CODES = {
    '00': 'Bulut gelişmesi gözlenmedi',
    '01': 'Bulutlar çözülüyor veya azalıyor',
    '02': 'Gökyüzünün görünüşü değişmedi',
    '03': 'Bulutlar oluşuyor veya gelişiyor',
    '04': 'Duman nedeniyle görüş azalması',
    '05': 'Pus (Haze)',
    '06': 'Yaygın toz',
    '07': 'İstasyon veya civarında toz veya kum fırtınası',
    '08': 'İyi gelişmiş toz veya kum hortumu',
    '09': 'Görüş mesafesini azaltan toz fırtınası veya kum fırtınası',
    '10': 'Sis (Mist)',
    '11': 'Sığ sis (Shallow fog patches)',
    '12': 'Sığ sis (More or less continuous)',
    '13': 'Şimşek görüldü, gök gürültüsü duyulmadı',
    '14': 'Civarda yağan fakat yere ulaşmayan yağış (Virga)',
    '15': 'İstasyondan uzakta (5km+) yağan yağış',
    '16': 'İstasyonda yağan yağış',
    '17': 'Gök gürültülü fırtına (Thunderstorm), yağış yok',
    '18': 'Fırtına (Squalls)',
    '19': 'Huni bulutu (Funnel cloud - Tornado veya su hortumu)',
    '20': 'Çisenti (Drizzle) veya kar taneleri (snow grains)',
    '21': 'Yağmur (Rain)',
    '22': 'Kar (Snow)',
    '23': 'Yağmur ve kar veya buz taneleri (ice pellets)',
    '24': 'Donan çisenti veya donan yağmur',
    '25': 'Sağanak yağmur (Rain shower)',
    '26': 'Kar sağanağı (Snow shower) veya yağmur ve kar sağanağı',
    '27': 'Dolu sağanağı (Hail shower) veya yağmur ve dolu sağanağı',
    '28': 'Sis veya buz sisi (Fog or ice fog)',
    '29': 'Gök gürültülü fırtına (Thunderstorm)',
    '30': 'Hafif veya orta şiddetli toz/kum fırtınası (azalıyor)',
    '31': 'Hafif veya orta şiddetli toz/kum fırtınası (değişmiyor)',
    '32': 'Hafif veya orta şiddetli toz/kum fırtınası (başladı/artıyor)',
    '33': 'Şiddetli toz/kum fırtınası (azalıyor)',
    '34': 'Şiddetli toz/kum fırtınası (değişmiyor)',
    '35': 'Şiddetli toz/kum fırtınası (başladı/artıyor)',
    '36': 'Hafif veya orta şiddetli kar fırtınası (drifting snow)',
    '37': 'Şiddetli kar fırtınası (drifting snow)',
    '38': 'Hafif veya orta şiddetli kar fırtınası (blowing snow)',
    '39': 'Şiddetli kar fırtınası (blowing snow)',
    '40': 'Uzakta sis veya buz sisi',
    '41': 'Parçalı sis veya buz sisi',
    '42': 'Sis veya buz sisi, gökyüzü görünüyor (inceliyor)',
    '43': 'Sis veya buz sisi, gökyüzü görünmüyor (inceliyor)',
    '44': 'Sis veya buz sisi, gökyüzü görünüyor (değişmiyor)',
    '45': 'Sis veya buz sisi, gökyüzü görünmüyor (değişmiyor)',
    '46': 'Sis veya buz sisi, gökyüzü görünüyor (kalınlaşıyor)',
    '47': 'Sis veya buz sisi, gökyüzü görünmüyor (kalınlaşıyor)',
    '48': 'Donan sis, gökyüzü görünüyor',
    '49': 'Donan sis, gökyüzü görünmüyor',
    '50': 'Hafif çisenti, aralıklı',
    '51': 'Hafif çisenti, sürekli',
    '52': 'Orta şiddetli çisenti, aralıklı',
    '53': 'Orta şiddetli çisenti, sürekli',
    '54': 'Şiddetli çisenti, aralıklı',
    '55': 'Şiddetli çisenti, sürekli',
    '56': 'Hafif donan çisenti',
    '57': 'Orta veya şiddetli donan çisenti',
    '58': 'Hafif yağmur ve çisenti',
    '59': 'Orta veya şiddetli yağmur ve çisenti',
    '60': 'Hafif yağmur, aralıklı',
    '61': 'Hafif yağmur, sürekli',
    '62': 'Orta şiddetli yağmur, aralıklı',
    '63': 'Orta şiddetli yağmur, sürekli',
    '64': 'Şiddetli yağmur, aralıklı',
    '65': 'Şiddetli yağmur, sürekli',
    '66': 'Hafif donan yağmur',
    '67': 'Orta veya şiddetli donan yağmur',
    '68': 'Hafif karla karışık yağmur veya çisenti',
    '69': 'Orta veya şiddetli karla karışık yağmur veya çisenti',
    '70': 'Hafif kar, aralıklı',
    '71': 'Hafif kar, sürekli',
    '72': 'Orta şiddetli kar, aralıklı',
    '73': 'Orta şiddetli kar, sürekli',
    '74': 'Şiddetli kar, aralıklı',
    '75': 'Şiddetli kar, sürekli',
    '76': 'Buz kristalleri (Diamond dust)',
    '77': 'Kar taneleri (Snow grains)',
    '78': 'İzole kar kristalleri',
    '79': 'Buz peletleri (Ice pellets)',
    '80': 'Hafif sağanak yağmur',
    '81': 'Orta veya şiddetli sağanak yağmur',
    '82': 'Aşırı şiddetli sağanak yağmur',
    '83': 'Hafif karla karışık yağmur sağanağı',
    '84': 'Orta veya şiddetli karla karışık yağmur sağanağı',
    '85': 'Hafif kar sağanağı',
    '86': 'Orta veya şiddetli kar sağanağı',
    '87': 'Hafif kar peletleri veya küçük dolu sağanağı',
    '88': 'Orta veya şiddetli kar peletleri veya küçük dolu sağanağı',
    '89': 'Hafif dolu sağanağı',
    '90': 'Orta veya şiddetli dolu sağanağı',
    '91': 'Hafif yağmur, gök gürültülü fırtına ile birlikte',
    '92': 'Orta veya şiddetli yağmur, gök gürültülü fırtına ile birlikte',
    '93': 'Hafif kar veya karla karışık yağmur, gök gürültülü fırtına ile birlikte',
    '94': 'Orta veya şiddetli kar veya karla karışık yağmur, gök gürültülü fırtına ile birlikte',
    '95': 'Hafif veya orta şiddetli gök gürültülü fırtına (yağmur/kar ile)',
    '96': 'Hafif veya orta şiddetli gök gürültülü fırtına (dolu ile)',
    '97': 'Şiddetli gök gürültülü fırtına (yağmur/kar ile)',
    '98': 'Toz/kum fırtınası ile birlikte gök gürültülü fırtına',
    '99': 'Şiddetli gök gürültülü fırtına (dolu ile)'
}

# Alçak Bulut (Low Cloud - CL) Kodları
CL_CODES = {
    '0': 'Alçak bulut yok',
    '1': 'Cumulus humilis veya fractus (iyi hava)',
    '2': 'Cumulus mediocris veya congestus',
    '3': 'Cumulonimbus calvus',
    '4': 'Stratocumulus (Cumuliform)',
    '5': 'Stratocumulus (Stratiform)',
    '6': 'Stratus nebulosus veya fractus',
    '7': 'Stratus fractus veya Cumulus fractus (kötü hava)',
    '8': 'Cumulus ve Stratocumulus (farklı seviyelerde)',
    '9': 'Cumulonimbus capillatus (örs bulutu ile)',
    '/': 'Alçak bulut gözlenemedi'
}

# Orta Bulut (Medium Cloud - CM) Kodları
CM_CODES = {
    '0': 'Orta bulut yok',
    '1': 'Altostratus translucidus',
    '2': 'Altostratus opacus veya Nimbostratus',
    '3': 'Altocumulus translucidus (tek seviyede)',
    '4': 'Altocumulus (parçalı, gelişiyor)',
    '5': 'Altocumulus (şeritler halinde, yayılıyor)',
    '6': 'Altocumulus (Cumulus\'tan oluşmuş)',
    '7': 'Altocumulus (çok katmanlı, opak)',
    '8': 'Altocumulus castellanus veya floccus',
    '9': 'Altocumulus (kaotik gökyüzü)',
    '/': 'Orta bulut gözlenemedi'
}

# Yüksek Bulut (High Cloud - CH) Kodları
CH_CODES = {
    '0': 'Yüksek bulut yok',
    '1': 'Cirrus fibratus veya uncinus',
    '2': 'Cirrus spissatus (parçalı)',
    '3': 'Cirrus spissatus (Cumulonimbus\'tan)',
    '4': 'Cirrus uncinus veya fibratus (yayılıyor)',
    '5': 'Cirrostratus (ufkun tamamını kaplamıyor)',
    '6': 'Cirrostratus (ufkun tamamını kaplıyor)',
    '7': 'Cirrostratus (tüm gökyüzünü kaplıyor)',
    '8': 'Cirrostratus (yayılmıyor)',
    '9': 'Cirrocumulus',
    '/': 'Yüksek bulut gözlenemedi'
}

# METAR/TAF Hava Hadisesi (Weather - WX) Kodları
WX_CODES = {
    "MI": "Sığ (Shallow)", "BC": "Parçalı (Patches)", "PR": "Kısmi (Partial)",
    "DR": "Alçak Sürüklenen (Low Drifting)", "BL": "Yüksek Sürüklenen (Blowing)",
    "SH": "Sağanak (Showers)", "TS": "Oraj (Thunderstorm)", "FZ": "Donan (Freezing)",
    "DZ": "Çisenti (Drizzle)", "RA": "Yağmur (Rain)", "SN": "Kar (Snow)",
    "SG": "Kar Taneleri (Snow Grains)", "IC": "Buz Kristalleri (Ice Crystals)",
    "PL": "Buz Peletleri (Ice Pellets)", "GR": "Dolu (Hail)", "GS": "Küçük Dolu (Small Hail/Snow Pellets)",
    "UP": "Bilinmeyen Yağış (Unknown Precipitation)", "BR": "Pus (Mist)", "FG": "Sis (Fog)",
    "FU": "Duman (Smoke)", "VA": "Volkanik Kül (Volcanic Ash)", "DU": "Yaygın Toz (Widespread Dust)",
    "SA": "Kum (Sand)", "HZ": "Pus (Haze)", "PY": "Püskürtü (Spray)",
    "PO": "Toz/Kum Girdapları (Dust/Sand Whirls)", "SQ": "Fırtına (Squalls)",
    "FC": "Huni Bulutu (Funnel Cloud)", "SS": "Kum Fırtınası (Sandstorm)", "DS": "Toz Fırtınası (Duststorm)"
}