# kurallar.py
# Bu dosya otomatik olarak oluşturulmuştur.
# Meteorolojik denetim kuralları ve hata mesajlarını içerir.

HATA_SOZLUGU = {
    "h1": "İstasyon Numarası (IIiii) Hatası.",
    "h2": "Ara rasatta İr=4 olmalı",
    "h3": "İr grubu hatalı kodlanmış",
    "h4": "İr=1 olduğu halde yağış grubu kodlanmamış",
    "h5": "İr=3 olduğu halde yağış grubu kodlanmış",
    "h6": "Ara rasatta yağış grubu kodlanmış",
    "h7": "Ana rasatta İr=4 kodlanmış",
    "h8": "İndikatör hatalı yada başka istasyonun rasadı",
    "h11": "İx=1 iken hadise grubu verilmemiş",
    "h12": "İx=2 iken hadise grubu verilmiş",
    "h13": "İx 1 ve 2 den farklı kodlanmış",
    "h17": "h hatalı kodlanmış",
    "h18": "h=/ verilmiş fakat 333 den sonra 89/hshs verilmemiş",
    "h22": "Görüş için Uygun olmayan kod rakamı verilmiş",
    "h26": "N= 0 iken bulut grubu verilmiş",
    "h27": "Bulut grubu verilmediğ halde N' ( sıfır ) dan farklı kodlanmış",
    "h28": "Bulutların toplam kapalığı N' e uymuyor",
    "h29": "Bulutların toplam kapalığı N' e uymuyor",
    "h30": "h=/ iken N=9 kodlanmamış",
    "h31": "h<>/  iken N=9 kodlanmış",
    "h32": "N=9 iken Ns=9 kodlanmamış",
    "h33": "N=9 iken C=/ kodlanmamış",
    "h34": "Toplam kapalılık ile bulut kapalılığı uyumsuz",
    "h35": "Toplam kapalılık ile bulut kapalılığı uyumsuz",
    "h36": "Toplam kapalılık \"/\" olarak kodlandı. Bulutluluk gözlem yapılmadı mı?",
    "h37": "dd kıstas dışı",
    "h38": "dd =00 iken ff=00 değil",
    "h39": "dd=00 değilken ff=00 verilmiş",
    "h43": "ff=00 iken dd yön verilmiş",
    "h44": "Rüzgar hız değeri limit dışı",
    "h47": "Kuru termometre işareti yanlış kodlanmış",
    "h48": "Kuru termometre sıcaklığı istasyon limitleri dışında",
    "h51": "İşba sıcaklığı işareti yanlış kodlanmış",
    "h52": "İşba sıcaklığı kuru termometre sıcaklığından büyük olamaz",
    "h53": "İşba sıcaklığı limit dışı",
    "h55": "Aktüel basınç istasyon limitleri dışında",
    "h58": "Denize indirilmiş basınç istasyon limitleri dışında",
    "h61": "Tandans karakteristiği 9 olamaz",
    "h62": "Tandans karakteristiği 0,4 veya 5 değilken değişim 0 olamaz",
    "h63": "Tandans karakteri 4 iken değişim 0 olur",
    "h64": "Tandans değişimi çok fazla",
    "h65": "Tandans değişimi 3 saat önceki basınçla uyumsuz",
    "h66": "Tandans değişimi tandans karakteri ile uyumsuz",
    "h70": "Yağış miktarı 000 kodlanmaz.",
    "h71": "Yağış miktarı çok fazla",
    "h72": "6 saat önce yağış olduğu halde bu saatte yağış miktarı verilmedi.",
    "h73": "Hadise kaydında yağış olduğu halde bu saatte yağış miktarı verilmedi veya yağış verildiği halde Hadise kaydı yapılmadı.",
    "h74": "tR 0 veya 1 den başka olamaz yada saat ile tR uyumsuz",
    "h75": "Ara rasatta yağış grubu verilmiş",
    "h76": "Hadise olmadığı halde yağış miktarı verilmiş. (Ayın 1 i ve 00z de yağış miktarı (6. grup) var ise bu uyarıyı dikkate alma.",
    "h78": "Halihazır hava 00 olamaz",
    "h79": "Görüş 10 Km.den az iken hadise verilmemiş",
    "h80": "İptal Edildi - WMO kurallarına göre ww=00-03 iken geçmişte hadise (W1>2) raporlanması normaldir.",
    "h81": "04: Rüyet 10 Km altında ve nisbi nem % 70' in altında olmalı",
    "h82": "05-06:Rüyet 1-10 Km arasında Nisbi nem % 70'in altında olmalı",
    "h83": "07-08-09: Fırtına yok, rüyet 8 Km veya altında olmalı",
    "h84": "10: Rüyet 1-10 Km Nisbi nem % 70 ve üzerinde olmalı",
    "h85": "11-12: Sığ sis (MIFG) hadiselerinde yatay görüş (VV) 1 km veya üzerinde olmalıdır. (Görüş < 1 km ise ww=40-49 kullanılmalıdır).",
    "h86": "17: Cb bulutu koda dahil edilmemiş",
    "h87": "28: Rasat zamanında görüş 1 km'nin üzerinde fakat son saat içerisinde görüş 1 km'nin altında olmalı (42-49 sona ermesi).",
    "h88": "30-31-32: Bu hadiselerde rüzgar hızı 28-40 Kt arasında olmalı",
    "h89": "30-31-32: Bu hadiselerde rüyet 1 km. altında olmalı",
    "h90": "33-34-35: Bu hadiselerde rüzgar hızı 41 Kt dan fazla olmalı",
    "h91": "33-34-35: Bu hadiselerde rüyet 1 km. altında olmalı",
    "h92": "36-37-38-39: Bu hadiselerde rüyet 8 km. veya altında olmalı",
    "h93": "40: Bu hadisede rüyet 1km.veya daha fazla ve 5 km.den az olmalı",
    "h94": "41: Bu hadisede rüyet 0 km.veya daha fazla ve 5 km.den az olmalı",
    "h95": "42-49: Bu hadiselerde rüyet 1 km. nin altında olmalı",
    "h96": "48-49: Bu hadiselerde sıcaklık 0°C veya daha düşük olmalı",
    "h97": "43-45-47-49: Bu hadiselerde toplam kapalılık 9 olmalıdır",
    "h98": "42-44-46-48: Bu hadiselerde toplam kapalılık 9 olamaz",
    "h99": "43-45-47-49: Bu hadiselerde 89/hshs grubu verilmelidir",
    "h100": "50-59: Bu hadiselerde St bulutu mutlaka olmalıdır",
    "h101": "56-57: Bu hadiselerde sıcaklık 5,4°C veya daha düşük olmalı",
    "h102": "66-67: Bu hadiselerde sıcaklık 5,4°C veya daha düşük olmalı",
    "h103": "68-69: Bu hadiselerde sıcaklık 8,5°C veya daha düşük olmalı",
    "h104": "70-79: Bu hadiselerde sıcaklık 6,5°C veya daha düşük olmalı",
    "h105": "74-75: Bu hadiselerde rüyet 2 km. ve altında olmalı",
    "h106": "80-94: Bu hadiselerde Cu-Cb bulutu mutlaka olmalıdır",
    "h107": "83-86: Bu hadiselerde sıcaklık 6,5°C veya daha düşük olmalı",
    "h108": "87-88: Bu hadiselerde sıcaklık 8,5°C veya daha düşük olmalı",
    "h109": "89-90: Bu hadiselerde Cb bulutu mutlaka olmalı",
    "h110": "95-99: Bu hadiselerde Cb bulutu mutlaka olmalı",
    "h111": "Yağış hadisesi verildiği halde Toplam kapalık 0 verilmiş",
    "h112": "13:Şimşek verildiği halde Cb bulutu verilmedi",
    "h113": "Hadise kaydıyla 7wwW1W2 uyumsuz Öneri: 7ww8W",
    "h114": "90-94: Arası hadiseler rasatta kodlanır ancak hadise kaydı 90-94 arası rakamla yapılmaz. (bu hata gün içindeki hadise kayıtları için)",
    "h116": "İkinci geçmiş hadise birinci geçmiş hadiseden büyük olamaz",
    "h117": "Geçmiş hava grubu hatalı",
    "h118": "Halihazır ve geçmiş havayı kodlamaya gerek yok.",
    "h120": "Alçak bulut toplam kapalığı Toplam kapalılıktan büyük olamaz",
    "h121": "Yüksek bulutlarda alçak bulut toplam kapalılığı 0 olur",
    "h122": "Alçak bulut kapalılığı hatalı",
    "h123": "Alçak bulutların toplam kapalılığı hatalı",
    "h124": "Orta bulut kapalılığı uyumsuz",
    "h125": "Bulut cinsleri koda dahil edilmemiş",
    "h128": "CL=3 veya 9 verilmiş fakat Cb bulutu verilmemiş",
    "h129": "CL=1,2 veya 8 verilmiş Cu verilmemiş",
    "h130": "CL=6 veya 7 verilmiş St verilmemiş",
    "h131": "CL=4 veya 5 verilmiş Sc verilmemiş",
    "h132": "Cb bulutu verilmiş fakat CL=9 veya 3 verilmemiş",
    "h133": "Sc bulutu verilmiş fakat CL=4 veya 5 verilmemiş",
    "h134": "Alçak bulut verilmiş, alçak bulut cinsi verilmemiş",
    "h135": "Alçak bulut cinsi verilmiş, alçak bulut verilmemiş. 1-3-5 kuralı uyuyor mu?",
    "h138": "Orta bulut verilmiş fakat orta bulut cinsi verilmemiş.",
    "h139": "Orta bulut cinsi verilmiş fakat orta bulut verilmemiş. 1-3-5 kuralı uyuyor mu?",
    "h140": "Ns bulutu verilmiş fakat orta bulut cinsi yanlış kodlanmış",
    "h141": "As bulutu verilmiş fakat orta bulut cinsi yanlış kodlanmış",
    "h142": "Ac bulutu verilmiş fakat orta bulut cinsi yanlış kodlanmış",
    "h146": "Yüksek bulut cinsi verilmiş fakat yüksek bulut verilmemiş.",
    "h147": "Yüksek bulut verilmiş fakat yüksek bulut cinsi verilmemiş.",
    "h148": "Cs bulutu verilmiş fakat cinsi hatalı kodlanmış",
    "h149": "Cc bulutu verilmiş fakat cinsi hatalı kodlanmış",
    "h150": "Ci bulutu verilmiş fakat cinsi hatalı kodlanmış",
    "h151": "Cs nin cinsi 7 verilmiş fakat 8/8 kapatmamış",
    "h152": "Cs 8/8 kapatmış fakat cinsi 7 verilmemiş",
    "h153": "CM veya CH da \"/\" kullanılmamış yada hatalı kullanılmış.",
    "h154": "1-3-5 kuralına uyulmamış",
    "h155": "Cu havayı 8/8 kapatmaz",
    "h156": "Cu havayı 8/8 kapatmaz",
    "h157": "Sc havayı 8/8 kapatmaz",
    "h158": "Sc havayı 8/8 kapatmaz",
    "h159": "Ac havayı 8/8 kapatmaz",
    "h162": "Nh = 8 verildiği halde orta ve yüksek bulut cinsi verilmiş",
    "h163": "Orta bulut kapalılığı 8/8 verildiği halde yüksek bulut cinsi verilmiş",
    "h164": "As gökyüzünü 6/8 den az kapatamaz",
    "h165": "Ns gökyüzünü 6/8 den az kapatamaz",
    "h166": "Cs gökyüzünü 6/8 den az kapatamaz",
    "h167": "Alçak bulut için bulut yüksekliği limit dışı",
    "h168": "Orta bulut için bulut yüksekliği limit dışı",
    "h169": "Orta bulut için bulut yüksekliği limit dışı",
    "h170": "Yüksek bulut için bulut yüksekliği limit dışı",
    "h171": "Yüksek bulut için bulut yüksekliği limit dışı",
    "h172": "Dikine rüyet için verilen yükseklik çok fazla",
    "h184": "Maksimum termometre işareti yanlış kodlanmış",
    "h185": "Maksimum sıcaklık son 12 saatteki sıcaklıktan düşük olamaz",
    "h186": "Maksimum sıcaklık koda dahil edilmemiş",
    "h187": "Maksimum sıcaklık limit dışı",
    "h190": "Minumum termometre işareti yanlış kodlanmış",
    "h191": "Minumum sıcaklık son 12 saatteki sıcaklıktan büyük olamaz",
    "h192": "Minumum sıcaklık koda dahil edilmemiş",
    "h193": "Minumum sıcaklık limit dışı",
    "h196": "Yerin hali ve toprak sıcaklık grubu koda dahil edilmedi",
    "h197": "Sıcaklık çok düşük olduğu halde yerin hali nemli yada ıslak verilmiş",
    "h198": "Havada yağış var iken uygun olmayan kod rakamı verilmiş",
    "h199": "Toprak termometre işareti yanlış kodlanmış",
    "h200": "Toprak sıcaklığı için yüksek bir değer",
    "h205": "Yerde kar var iken yerin hali ve toplam kar grubu verilmedi",
    "h206": "Yerde ölçülebilir kar veya buz örtüsü olmalıdır",
    "h207": "Toplam kar kalınlığı çok fazla",
    "h212": "Buharlaşma grubu koda dahil edilmedi",
    "h213": "İstasyon buharlaşma aletinin kodunu kontrol edin.",
    "h214": "Buharlaşma miktarı çok fazla",
    "h219": "Güneşlenme süresi koda dahil edilmedi",
    "h220": "Güneşlenme süresi çok fazla",
    "h224": "Radyasyon tipi için ülkemizde 2 den başka rakam kodlanmaz",
    "h225": "Radyasyon miktarı 0 olamaz",
    "h226": "Radyasyon miktarı çok fazla",
    "h230": "Daha önceki rasatlarda yağış olduğu halde toplam yağış verilmedi",
    "h231": "Toplam yağışta 0000 verilmez",
    "h232": "Toplam yağış ile daha önceki yağış miktarları uyumsuz",
    "h233": "Toplam yağış miktarı çok fazla",
    "h238": "Hamle verilmesi için 10Kt ve daha fazla fark olmalı",
    "h239": "Hamle için çok yüksek bir değer",
    "h242": "Taze kar için yüksek bir değer",
    "h246": "17 Hadisesinin 20'li hadiselerden önceliği vardır",
    "h247": "Büyük Numaralı hadise halihazır hava grubunda verilmelidir",
    "h248": "1-2-3 Nolu hadiseler bu grubta verilmez",
    "h249": "Hadise kaydında ikinci hadise olmasına rağmen 960. grubu koda dahil etmediniz.",
    "h252": "Sıcaklık grubu koda dahil edilmedi",
    "h253": "İşba sıcaklık grubu koda dahil edilmedi",
    "h254": "Aktüel basınç grubu koda dahil edilmedi",
    "h255": "Denize indirilmiş basınç grbu koda dahil edilmedi",
    "h256": "Tandans grubu koda dahil edilmedi",
    "h257": "Bulut grubu koda dahil edilmedi",
    "h258": "Maksimum sıcaklık grubu koda dahil edilmedi",
    "h259": "Minumum sıcaklık grubu koda dahil edilmedi",
    "h260": "Toprak sıcaklık grubu koda dahil edilmedi",
    "h261": "924 grubu koda dahil edilmedi.",
    "h262": "Hadise Kayıtlarında eksiklik veya uyumsuzluk var kontrol edelim.",

    "h263": "Rasat saati formatı hatalı",
    "h264": "İstasyon yüksekliği eksik veya hatalı",
    "h265": "Sensör verisi eksik",
    "h266": "Rasat verisi (RASATLAR) eksik veya okunamadı",
    "h267": "Toprak minimum sıcaklığı (Tg), havadaki minimum sıcaklıktan (Tn) büyük olamaz (Tg <= Tn olmalıdır).",
    "h268": "18: Squall (Fırtına) hadisesinde rüzgar hızı 22 kt veya daha fazla olmalıdır.",
    "h269": "20-29 Arası sona eren hadise verilmiş ancak METAR geçmişinde (veya önceki saatte) bu durumu doğrulayan bir hadise bulunamadı.",
    
    # --- MANTIK, ÇAPRAZ VE VALİDATOR KURALLARI (h270 ve Sonrası) ---
    "h270": "Sıcaklık Uyumsuzluğu (SİNOPTİK vs METAR)",
    "h271": "İşba Sıcaklığı (Çiğ Noktası) Uyumsuzluğu (SİNOPTİK vs METAR)",
    "h272": "Nem Yüzdesi Uyumsuzluğu (SİNOPTİK vs METAR)",
    "h273": "Rüzgar Hızı Uyumsuzluğu (SİNOPTİK vs METAR)",
    "h274": "Rüzgar Yönü Uyumsuzluğu (SİNOPTİK vs METAR)",
    "h275": "Sakin Rüzgar Çelişkisi: Rüzgar hızı 0 iken yön girilmiş",
    "h276": "910 Grubu Hatası: Anlık hamle, normal rüzgar hızından küçük olamaz",
    "h277": "911 Grubu Hatası: Maksimum hamle mantık hatası",
    "h278": "Toplam Bulut Kapalılığı Uyumsuz (SİNOPTİK N vs METAR T.Kp)",
    "h279": "METAR'da ölçülemeyen (///) bulut varken SİNOPTİK'te yükseklik girilmiş",
    "h280": "Bulut Cinsi Uyumsuzluğu (SİNOPTİK CL/CM/CH vs METAR)",
    "h281": "Görüş Mesafesi düşük ancak kısıtlayıcı hadise raporlanmamış",
    "h282": "Sis hadisesi girilmiş ancak görüş mesafesi 1 km veya üzerinde",
    "h283": "Çapraz Görüş Çelişkisi (SİNOPTİK VV vs METAR Hakim Görüş)",
    "h284": "METAR CAVOK iken SİNOPTİK'te 1500m (5000ft) altında bulut girilmiş",
    "h285": "METAR CAVOK iken SİNOPTİK'te Kümülonimbüs (CB/TCU) girilmiş",
    "h286": "SİNOPTİK'te Oraj kodlanmış ancak METAR'da TS raporlanmamış",
    "h287": "SİNOPTİK'te Dolusuz Oraj kodlanmış ancak METAR'da Dolu var",
    "h288": "SİNOPTİK'te Dolulu Oraj kodlanmış ancak METAR'da Dolu yok",
    "h289": "METAR'da TS+Dolu var ancak SİNOPTİK ww kodu uyumsuz",
    "h290": "Dolu Çapı (924) Eksikliği veya Yersiz Kodlanması",
    "h291": "Donduran Yağış/Çisenti (FZ) Çapraz Uyumsuzluğu",
    "h292": "Kar Yağışı (SN) Çapraz Uyumsuzluğu",
    "h293": "Pus (BR) Çapraz Uyumsuzluğu",
    "h294": "Duman/Volkanik Kül Çapraz Uyumsuzluğu",
    "h295": "Toz Pusu (HZ) Çapraz Uyumsuzluğu",
    "h296": "Kum/Toz Fırtınası Çapraz Uyumsuzluğu",
    "h297": "Toz Şeytanı (PO) Çapraz Uyumsuzluğu",
    "h298": "Sağanak Yağış (SH) Çapraz Uyumsuzluğu",
    "h299": "Sürüklenen/Savrulan Kar Çapraz Uyumsuzluğu",
    "h300": "Kar Savrulması (BLSN/DRSN) için yüzey rüzgarı yetersiz",
    "h301": "Windshear (WS) için yüzey rüzgarı veya hamle yetersiz",
    "h302": "Gökyüzü görünmez (N=9) ancak görüş yüksek veya kapatıcı hadise yok",
    "h304": "Donduran hadise (FZ) raporlanmış ancak hava sıcaklığı çok yüksek",
    "h305": "Kar yağışı (SN) raporlanmış ancak hava sıcaklığı kar için çok yüksek",
    "h306": "QNH - QFE İndirgeme mantık hatası (Rakım Uyumsuzluğu)",
    "h307": "Şifreli SİNOPTİK mesajı ile Excel'e girilen veriler çelişiyor",
    "h308": "Şifreli METAR mesajı ile Excel'e girilen veriler çelişiyor",
    "h309": "METAR'a göre hesaplanan Geçmiş Hava beklentisi ile SİNOPTİK W1/W2 kodları uyumsuz",
    "h310": "Şifreli SİNOPTİK veya METAR format kurallarına uymuyor (Eksik veya hatalı grup)",
    "h311": "Gökyüzü görünmüyor (N=9) iken dikine görüşü temsil eden 'h' değeri 9 (>2500m) olamaz.",
    "h312": "Gökyüzü görünmüyor (N=9) olarak kodlanmış ancak yatay görüş mesafesi oldukça yüksek.",
    "h313": "N=9 (Gökyüzü görünmüyor) olarak kodlanmış ancak gökyüzünü kapatacak bir hadise raporlanmamış.",
    "h314": "Alçak/Orta Bulut kapalılığı görünmüyor (Nh=9) iken Toplam Bulut Kapalılığı (N) da 9 olmalıdır.",
    "h315": "Yağış miktarı (RRR) kodlanmış ancak Halihazır (ww) veya Geçmiş Hava (W1, W2) gruplarında yağış işlenmemiş.",
    "h316": "12 saatlik toplam yağış, periyot içindeki 6 saatlik miktardan küçük olamaz.",
    "h317": "24 saatlik toplam yağış, periyot içindeki ölçülen miktardan küçük olamaz.",
    "h318": "Sürekli yağış raporlanmış ancak havayı kapatan kalın tabakalı bulut kodlanmamış.",
    "h319": "Kümülonimbüs (Cb) bulutu sağanak karakterli yağış üretir, ancak halihazır hava sürekli/aralıklı yağış olarak girilmiş.",
    "h320": "Uzakta/ulaşmayan yağış kodlanmış ancak gökyüzü bulutsuz (N=0) girilmiş.",
    "h321": "Şimşek raporlanmış ancak Cb veya Ac Castellanus bulutu kodlanmamış.",
    "h322": "Geçmiş hava 1 (W1) boş bırakılmış ancak Geçmiş hava 2 (W2) kodlanmış.",
    "h323": "METAR CAVOK/Görüş ile Sinoptik VV uyumsuz.",
    "h324": "METAR CAVOK iken Sinoptik'te 1500m altında bulut kodlanamaz.",
    "h325": "METAR CAVOK iken Sinoptik'te CB/TCU kodlanamaz.",
    "h326": "METAR geçmişinde yağış raporlanmış, ancak Sinoptik geçmiş havada (W1/W2) yağış kodlanmamış.",
    "h327": "METAR geçmişinde Sis raporlanmış, ancak Sinoptikte kodlanmamış.",
    "h328": "Pus (BR) hadisesinin WMO formatında geçmiş hava kodu yoktur, 4 girilemez.",
    "h329": "Sis (4) kodlanmış ancak METAR'larda Sis bulunamadı.",
    "h330": "METAR geçmişinde Kum/Toz Fırtınası raporlanmış, ancak Sinoptikte kodlanmamış.",
    "h331": "Toz Pusu/Duman vb. hadiselerinin WMO formatında geçmiş hava kodu yoktur, 3 girilemez.",
    "h332": "Kum/Toz Fırtınası (3) kodlanmış ancak METAR'larda bulunamadı.",
    "h333": "METAR geçmişinde Oraj raporlanmış, ancak Sinoptikte kodlanmamış.",
    "h334": "Yakın Geçmiş Hadisesi (RE) raporlanmış ancak SİNOPTİK'te karşılığı yok.",
    "h335": "Yağışlı Yakın Geçmiş Hadisesi var, RRR boş bırakılamaz.",
    "h336": "Yakın Geçmişte Oraj var, W1/W2'den biri 9 olmalıdır.",
    "h337": "Yakın Geçmişte Sağanak var, W1/W2'den biri 8 olmalıdır.",
    "h338": "Yakın Geçmişte Kar var, W1/W2'den biri 7 olmalıdır.",
    "h339": "Yakın Geçmişte Donduran Yağış var, W1/W2'den biri 5, 6 veya 7 olmalıdır.",
    "h340": "METAR geçmişinde rüzgar hamlesi (Gust/G) raporlanmış, ancak Sinoptikte 910/911 grubu kodlanmamış.",
    "h341": "Gün içinde Dolu (GR) veya Küçük Dolu (GS) raporlanmış, ancak Sinoptikte 960 grubu kodlanmamış.",
    "h342": "Gün içinde Yoğun Sis (FG/FZFG) raporlanmış, ancak Sinoptikte 960 grubu kodlanmamış.",
    "h343": "931 (Taze Kar) grubu girilmiş ancak son 6 saatlik periyotta kar yağışı raporlanmamış.",
    "h344": "Kar kalınlığı çok ekstrem bir değer olarak girilmiş.",
    "h345": "İptal Edildi.",
    "h346": "Kar kalınlığı çok ekstrem bir değer olarak girilmiş (931).",
    "h347": "Ana sinoptik periyodunda (son 6 saat) kar (SN vb.) raporlanmış, ancak 931 (Taze Kar) grubu girilmemiş.",
    "h348": "Yağmurdan Kara (veya tersi) dönüşüm yaşanmış, ww=68/69 kontrol edilmeli.",
    "h349": "Donduran Yağış raporlanmış, ww kodlaması kontrol edilmeli.",
    "h350": "Buz/Kar Taneleri raporlanmış, ww kodlaması kontrol edilmeli.",
    "h351": "Toz/Kum Fırtınası raporlanmış, ww kodlaması kontrol edilmeli.",
    "h352": "Orajalı Fırtına (SQ) raporlanmış, ww=18 kodlaması kontrol edilmeli.",
    "h353": "METAR'da Alçak Bulut raporlanmış ancak SİNOPTİK'te kodlanmamış.",
    "h354": "METAR'da Orta Bulut raporlanmış ancak SİNOPTİK'te kodlanmamış.",
    "h355": "METAR'da Yüksek Bulut raporlanmış ancak SİNOPTİK'te kodlanmamış.",
    "h356": "METAR'da Kümülonimbüs (CB/TCU) mevcut, ancak SİNOPTİK'te bulunamadı.",
    "h357": "METAR'da Alçak veya Orta bulut katmanı var ancak SİNOPTİK Nh 0 kodlanmış.",
    "h358": "SİNOPTİK Toplam Bulut Kapalılığı (N) ile METAR Toplam Bulut Kapalılığı uyuşmuyor.",
    "h359": "924 (Dolu Çapı) grubu girilmiş ancak dolu hadisesi bulunamadı.",
    "h360": "Dolu çapı çok ekstrem bir değer olarak girilmiş.",
    "h361": "METAR'a göre hesaplanan Geçmiş Hava beklentisi ile SİNOPTİK W1/W2 kodları uyumsuz.",
    "h362": "Şifreli SİNOPTİK veya METAR format kurallarına uymuyor (Eksik veya hatalı grup).",
    "h363": "İlgili ana/ara sinoptik saatinde rasat verisi bulunamadı (Tüm zorunlu parametreler eksik).",
    "h364": "METAR'da Donduran Yağış/Çisenti (FZRA/FZDZ) var, ancak Sinoptik ww kodu uyumsuz.",
    "h365": "METAR'da Kar (SN) raporlanmış, ancak Sinoptik ww kodu uyumsuz.",
    "h366": "METAR'da Pus (BR) var, ancak Sinoptik ww kodu uyumsuz.",
    "h367": "METAR'da Duman/Volkanik Kül (FU/VA) var, ancak Sinoptik ww kodu uyumsuz.",
    "h368": "METAR'da Toz Pusu (HZ) var, ancak Sinoptik ww kodu uyumsuz.",
    "h369": "METAR'da Kum/Toz Fırtınası (SS/DS) var, ancak Sinoptik ww kodu uyumsuz.",
    "h370": "METAR'da Toz Şeytanı (PO) var, ancak Sinoptik ww kodu uyumsuz.",
    "h371": "METAR'da Sağanak Yağış (SH..) var, ancak Sinoptik ww kodu uyumsuz.",
    "h372": "METAR'da Sürüklenen/Savrulan Kar (BLSN/DRSN) var, ancak Sinoptik ww kodu uyumsuz.",
    "h373": "Kar Savrulması (BLSN/DRSN veya ww) raporlanmış ancak rüzgar hızı çok düşük.",
    "h374": "931 (Taze Kar) grubu girilmiş ancak son 6 saatlik periyotta kar yağışı (SN/SG vb.) veya kar geçmiş havası (W1/W2=7) raporlanmamış.",
    "h375": "WMO Kuralı: Rüzgar yönü değişken (dd=99) iken rüzgar hızı 5 knot'tan büyük olamaz.",
    "h376": "0000 ve 1200 GMT rasatlarında tR=1 (6RRR1), 0600 ve 1800 GMT rasatlarında tR=2 (6RRR2) olmalıdır.",
    "h377": "METAR Görüş değeri ile Sinoptik VV değeri çapraz kontrolde uyuşmuyor.",
    "h378": "ww=01, 02 veya 03 kodlamasında, önceki rasatlara göre bulutluluk (N) değişimi ile çelişki var.",
    "h379": "Şimşek (ww=13) kodlanmış ancak Oraj (TS/W1=9 vb.) ile çelişen veya eksik değerlendirme durumu var.",
    "h380": "METAR'da Donduran Sis (FZFG) var, ancak Sinoptik ww kodu uyumsuz.",
    "h381": "METAR'da Sis (FG) var, ancak Sinoptik ww kodu uyumsuz.",
    "h382": "WMO Öncelik Hatası: Ana ww grubu ile 960 grubu arasında öncelik çelişkisi var.",
    "h383": "Ana sinoptik saatlerde (0000, 0600, 1200, 1800 GMT) yağış olsun veya olmasın 6RRRtR grubu (Yağış Miktarı) zorunludur."
}

def hata_mesaji_getir(hata_kodu):
    """Verilen hata koduna karşılık gelen mesajı döner."""
    return HATA_SOZLUGU.get(hata_kodu, "Bilinmeyen Hata")
